version: "3.8"

services:
  backend:
    build:
      context: ..
      dockerfile: docker/backend.Dockerfile
    container_name: astra-backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=astra

  ui:
    build:
      context: ..
      dockerfile: docker/ui.Dockerfile
    container_name: astra-ui
    ports:
      - "80:80"
    depends_on:
      - backend

  db:
    image: mysql:8
    container_name: astra-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: astra
    ports:
      - "3307:3306"
